- name: Decomission from puppet & forema/katello
  hosts: localhost
  vars:
    node: "{{ node }}" #"rcsa-it-dc-01"
    token: "0Rl1vQtZOD2ntoQ36tlNe0ujTM5WSIdWpmHvmGT1on6o"
    tstamp: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"
    user: "admin"
    pwd: Password1
    domain: "{{domain}}" #"lab.com"
    katello_server_url: "https://form-it-dc-01.lab.com"
    puppet_server_url: "https://puppet.lab.com:8081/pdb"
    organization: Lab
  tasks:

    - name: Deativate node
      uri:
        url: "{{ puppet_server_url }}/cmd/v1"
        method: POST
        body_format: json
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          X-Authentication: "{{ token }}"
        body:
          command: deactivate node
          version: 3
          payload:
            certname: "{{ node }}.{{ domain }}"
            producer_timestamp: "{{ tstamp }}"
      register: result
      changed_when: result.status == 200


    - name: Delete note from puppet
      uri:
        url: "{{ puppet_server_url }}/admin/v1/cmd"
        method: POST
        body_format: json
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          X-Authentication: "{{ token }}"
        body:
          command: delete
          version: 1
          payload:
            certname: "{{ node }}.{{ domain }}"
      register: result
      changed_when: result.status == 200

#    - name: Print response body
#      debug:
#        var: result.json

    - name: remove host from foreman/katello
      theforeman.foreman.host:
          validate_certs: false
          username: "{{ user }}"
          password: "{{ pwd }}"
          server_url: "{{ katello_server_url }}"
          organization: "{{ organization }}"
          name: "{{ node }}.{{ domain }}"
          state: absent

    - name: Shutdown "{{ ansible_hostname }}""
      community.vmware.vmware_guest_powerstate:
        hostname: "{{vcenter}}"
        username: "{{vc_user}}"
        password: "{{vc_pwd}}"
        name: "{{ node | upper}}" #assuming that vm name is in uppercase
        state: shutdown-guest
        validate_certs: false
      delegate_to: localhost
      register: deploy  

- name: DNS
  hosts: "{{ dc }}"
#  vars:
#    node: "rcsa-it-dc-01"    
#    domain: "lab.com" 
  tasks:
    - name: Remove DNS Record
      community.windows.win_dns_record:
        name: "{{ node }}"
        type: "A"
        state: absent
        zone: "{{ domain }}"
